### PR TITLE
Explain the controller on the IIWA to achieve the desired force applied at the end-effector.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/405)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@lujieyang for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/405#-:-MqLzQNI3ASt5IBVkleL:b-ioxum3)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @lujieyang)

**Comment by lujieyang** [comment]
___
*[doc/pole_balance.tex, line 95 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/405#-MqMwFFB7Hbz_L1VIkYC:-MqMwFFB7Hbz_L1VIkYD:b-2r58p1) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/e060c9ecaed5726f914faacbdda088cff9cefed1/doc/pole_balance.tex#L95)):*
> ```TeX
> 	\leftidx{^W}{J}^E\ddot{q}_{iiwa} + \leftidx{^W}{\dot{J}}^E\dot{q}_{iiwa} = \leftidx{^W}{a}^E_{des}\label{eq:iiwa_ee_acceleration}
> \end{align}
> where $\leftidx{^W}{J}^E$ is the Jacobian of the end-effector written in the world frame. $\leftidx{^W}{a}^E_{des}$ is the desired acceleration of the IIWA end-effector frame $E$ in the world frame $W$. This acceleration includes both the linear acceleraton $\ddot{x}_A, \ddot{y}_A, \ddot{z}_A$, together with the desired angular acceleration (which can be computed from a PD law using the orientation error).
> ```

To make things simpler, we might want to require angular accelerations to be constantly 0?

**Review by lujieyang — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/405)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai and @lujieyang)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/405)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @lujieyang)

___
*[doc/pole_balance.tex, line 95 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/405#-MqMwFFB7Hbz_L1VIkYC:-MqNexsd4KVqYId2BKVI:b-66s96x) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/e060c9ecaed5726f914faacbdda088cff9cefed1/doc/pole_balance.tex#L95)):*
<details><summary><i>Previously, lujieyang wrote…</i></summary><blockquote>

To make things simpler, we might want to require angular accelerations to be constantly 0?
</blockquote></details>

Done. I added more explanation here, on why using 0 acceleration might work, but could be problematic if the end-effector has noticeable angular velocity.

**Review by lujieyang — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/405)* status: all files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/405)* status: all files reviewed, 1 unresolved discussion (waiting on @lujieyang)

___
*[doc/pole_balance.tex, line 98 at r2](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/405#-MqP_oAZ3CQGKnG3RtmR:-MqPy75O6jgjDLchaDZM:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/752ec8d3836159e26da46990826b5234c6aa5e0e/doc/pole_balance.tex#L98)):*
<details><summary><i>Previously, lujieyang wrote…</i></summary><blockquote>

 desired end-effector angular acceleration
</blockquote></details>

Done.

**Review by lujieyang — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/405)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
