### PR TITLE
Add Pole class with dynamics.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@lujieyang for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400#-:-Mq2Jfbd3KPtGzZC6eqM:b-ioxum3)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @lujieyang)

**Comment by lujieyang** [comment]
___
*[neural_network_lyapunov/examples/pole/pole.py, line 12 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400#-Mq69xN8BAKOI00hysp1:-Mq69xN8BAKOI00hysp2:b-1dkx26) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/64c1871cbe2e0fc0ac3fff2e24bc95c41314d57e/neural_network_lyapunov/examples/pole/pole.py#L12)):*
> ```Python
>     system is the force applied on the end-effector.
>     The state of the system is:
>         delta horizontal position from the end-effector to the sphere.
> ```

Maybe clarify the (number of) variables with (x_AB, y_AB)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @lujieyang)

___
*[neural_network_lyapunov/examples/pole/pole.py, line 12 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400#-Mq69xN8BAKOI00hysp1:-Mq6DOFsASuqv6Nd9XHV:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/64c1871cbe2e0fc0ac3fff2e24bc95c41314d57e/neural_network_lyapunov/examples/pole/pole.py#L12)):*
<details><summary><i>Previously, lujieyang wrote…</i></summary><blockquote>

Maybe clarify the (number of) variables with (x_AB, y_AB)
</blockquote></details>

Done.

**Comment by lujieyang** [comment]
___
*[neural_network_lyapunov/examples/pole/test/test_pole.py, line 27 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400#-Mq6DxL42HHVSmKXllCX:-Mq6DxL5957sMSD4rAFK:b9wgps9) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/64c1871cbe2e0fc0ac3fff2e24bc95c41314d57e/neural_network_lyapunov/examples/pole/test/test_pole.py#L27)):*
> ```Python
>         # now simulate the pole system under zero external force. The total
>         # energy should be conserved.
>         # The state x0 is [x/y/z/ position of the end-effector pole_state]
> ```

Add "," to separate end-effector position and pole state

**Review by lujieyang — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400)* status: all files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @lujieyang)

___
*[neural_network_lyapunov/examples/pole/test/test_pole.py, line 27 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400#-Mq6DxL42HHVSmKXllCX:-Mq6HnPOCuZFEIHSaabb:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/64c1871cbe2e0fc0ac3fff2e24bc95c41314d57e/neural_network_lyapunov/examples/pole/test/test_pole.py#L27)):*
<details><summary><i>Previously, lujieyang wrote…</i></summary><blockquote>

Add "," to separate end-effector position and pole state
 
</blockquote></details>

Done.

**Review by lujieyang — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/400)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
