### PR TITLE
Learn a relu model to approximate the Pole dynamics

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@lujieyang for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412#-:-Mqrgbha92L41ozfaA7X:b-ioxum3)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lujieyang)

**Comment by lujieyang** [comment]
___
*[neural_network_lyapunov/examples/pole/learn_relu_dynamics.py, line 37 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412#-MqtJAEEDxyrIuRAhK7T:-MqtJAEEDxyrIuRAhK7U:b-qua06l) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/001f72b6f9df560c4ba1bb7f686452cee6f419a4/neural_network_lyapunov/examples/pole/learn_relu_dynamics.py#L37)):*
> ```Python
>                 constant_control_steps=1)[0]
> 
>     x_next_is_nan = torch.any(torch.isnan(x_next_samples), dim=1)
> ```

Why would x_next be nan? When the mass matrix M loses rank?

**Review by lujieyang — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412)* status: all files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lujieyang)

___
*[neural_network_lyapunov/examples/pole/learn_relu_dynamics.py, line 37 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412#-MqtJAEEDxyrIuRAhK7T:-Mqtm3puBsAXMOPWbW56:b92qhsn) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/001f72b6f9df560c4ba1bb7f686452cee6f419a4/neural_network_lyapunov/examples/pole/learn_relu_dynamics.py#L37)):*
<details><summary><i>Previously, lujieyang wrote…</i></summary><blockquote>

Why would x_next be nan? When the mass matrix M loses rank?
</blockquote></details>

I add documentation to explain why x_next can be nan. This comes from when the current x_AB, y_AB has norm close to pole length and when the velocity is large (namely the azimuth angle is very small, the pole is close to falling over with large velocity), then the next x_AB, y_AB might have norm larger than pole length, which is not physically valid, and return a Nan.

**Comment by lujieyang** [comment]
___
*[neural_network_lyapunov/examples/pole/learn_relu_dynamics.py, line 37 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412#-MqtJAEEDxyrIuRAhK7T:-Mqu5IEd50-sup7IpSNW:b-uqmdcl) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/001f72b6f9df560c4ba1bb7f686452cee6f419a4/neural_network_lyapunov/examples/pole/learn_relu_dynamics.py#L37)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I add documentation to explain why x_next can be nan. This comes from when the current x_AB, y_AB has norm close to pole length and when the velocity is large (namely the azimuth angle is very small, the pole is close to falling over with large velocity), then the next x_AB, y_AB might have norm larger than pole length, which is not physically valid, and return a Nan.
</blockquote></details>

Why wouldn't such scenario be eliminated by the criteria for the azimuth angle to be larger than 45?

**Review by lujieyang — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai and @lujieyang)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lujieyang)

___
*[neural_network_lyapunov/examples/pole/learn_relu_dynamics.py, line 37 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412#-MqtJAEEDxyrIuRAhK7T:-Mqu5uF1-fGM8VkfjdOc:b-vjp0oz) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/001f72b6f9df560c4ba1bb7f686452cee6f419a4/neural_network_lyapunov/examples/pole/learn_relu_dynamics.py#L37)):*
<details><summary><i>Previously, lujieyang wrote…</i></summary><blockquote>

Why wouldn't such scenario be eliminated by the criteria for the azimuth angle to be larger than 45?
</blockquote></details>

This is a safety guard. In the future we might relax that constraint that azimuth angle can gets smaller, and this scenario might be triggered with smaller azimuth angle.

**Comment by lujieyang** [comment]
:lgtm:

**Review by lujieyang — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/412)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
